### ISSUE TITLE
[ui] Dublin Core meta-data issues

### ISSUE THREAD

**Issue by pietercolpaert** [tdt/core#134]
When implementing a form using a vocabulary, there should be very good user feedback, auto-completions, client-side validation, etc. This is to make sure that the data is entered just as we want it: linked to entities, an element from a list, and so on. Only a few are just free fields, such as "description".
- [ ] Title - Shouldn't be empty
- [ ] Should we make description a text area?
- [*] Subject - see issue #131 
- [ ] Publisher - Should be a URI (found by autocompletion, although I wouldn't know where to get a list) or **should be more fields describing the publisher (name, affiliation, email address...)**.
- [ ] Contributor - leave this out. Too hard to implement before feature freeze: can be multiple contributors, would also need a URI or a description (name, affiliation, email address...)
- [ ] Date - automatically fill out today, use a calendar, make sure yourself it's in iso8601
- [ ] Format - leave this out. We're publishing it as a lot of formats anyway, so we know what formats we have. The user shouldn't tell us.
- [ ] Leave out identifier - we're creating one ourselves
- [ ] Leave out source or make sure this is a URI if you really want to keep it in
- [ ] Language: autocomplete!
- [ ] Relation - can be multiple as well - would leave out for now
- [ ] Coverage: very interesting! Use a map to make people select the coverage!
- [ ] Rights: a uri to the license is needed
