### ISSUE TITLE
DCAT-AP

### ISSUE THREAD

**Issue by dive-michiel** [tdt/core#256]
## DCAT-AP

DCAT-AP is a standard by the European Commission to foresee interoperability amongst open data portals. It follows the W3C DCAT specification, but is more clear about what properties are mandatory and which are recommended.

Image: https://joinup.ec.europa.eu/system/files/project/f9/42/c0/DCAT-AP_Final_v1.00.png
## Plans

We will integrate DCAT-AP in _short-term_ and foresee all mandatory and recommended fields in the image linked above. We also foresee to have at install time a custom document with all categories (dcat:themeTaxonomy) as URIs.

In _long-term_ (not included in this issue) we also foresee DCAT-AP support for adding resources through JSON-LD documents.
## Tasks
- [x] General DCAT properties of the Catalog
- [ ] dcat:themeTaxonomy default list (+ seed) + configurable in general settings (multiple per catalog)
- [x] DCAT properties of datasets + required
- [x] dcat:keywords on datasets (multiple literals)
- [x] Admin: required DCAT properties
- [x] dcat:publisher
- [x] dcat distributions (Pick one formatter: JSON(LD))
- [x] Title fallback
